.gitignore
Makefile
README.md
cmd/cni-noop/cni-noop.go
cmd/cnispawn/cnispawn.go
cmd/kubeadm-systemd/kubeadm-systemd.go
etc/kubeadm.yaml
glide.lock
glide.yaml
pkg/bootstrap/bridge.go
pkg/bootstrap/container.go
pkg/bootstrap/kubernetes.go
pkg/cnispawn/netns.go
pkg/cnispawn/spawn.go
pkg/distribution/registry.go
pkg/nspawntool/image.go
pkg/nspawntool/run.go
pkg/ssh/connection.go
pkg/ssh/key.go
pkg/ssh/kubeadm.go
pkg/utils/token.go
scripts/bootstrap.sh
scripts/init.sh
scripts/weave-daemonset.yaml

A small CLI tool for downloading CentOS container image, spawning the containers, configuring a Docker daemon on them and setting up k8s cluster by kubeadm (via Ansible).
---
TODO:

kubeadm-nspawn: Add a CLI for spawning the kubeadm dev environments

---

Makefile
cmd/nspawn-runc/nspawn-runc.go
pkg/bootstrap/container.go
pkg/nspawntool/image.go
scripts/bootstrap.sh

~~`cmd/runc-wrapper`~~ `cmd/nspawn-runc` wraps docker's `runc` as a custom runtime
and injects the `--no-new-keyring` flag when the create or run subcommands are executed.
Closes #21

Wrap docker-runc-current to avoid keyctl syscall

---

cmd/kubeadm-nspawn/kubeadm-nspawn.go

When systemd-nspawn is not running, there are no nodes. Don't
dereference the first node.
Symptoms:
```
| $ sudo ./kubeadm-nspawn init
| 2017/06/14 14:33:09 Warning: experimental!
| panic: runtime error: index out of range
|
| goroutine 1 [running]:
| panic(0x556b46226c80, 0xc4200100f0)
| 	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
| main.runInit(0xc420073440, 0x556b46746dc8, 0x0, 0x0)
| 	/go/src/github.com/kinvolk/kubeadm-nspawn/cmd/kubeadm-nspawn/kubeadm-nspawn.go:116 +0x4da
| github.com/kinvolk/kubeadm-nspawn/vendor/github.com/spf13/cobra.(*Command).execute(0xc420073440, 0x556b46746dc8, 0x0, 0x0, 0xc420073440, 0x556b46746dc8)
| 	/go/src/github.com/kinvolk/kubeadm-nspawn/vendor/github.com/spf13/cobra/command.go:647 +0x443
| …
```

kubeadm-nspawn: init: fix panic, index out of range

---

pkg/nspawntool/kubeadm.go

`join*.sh` needs to run with an additional parater for the master IP. Otherwise it could not run correctly.
Fixes https://github.com/kinvolk/kubeadm-nspawn/issues/48

pkg/nspawntool: give the masterIP parameter to join*.sh

---

Vagrantfile
cmd/kube-spawn/kube-spawn.go
glide.lock
glide.yaml
scripts/vagrant-mod-env.sh
scripts/vagrant-setup-env.sh

This PR contains multiple fixes to be able to run `kube-spawn` inside a Vagrant VM. The most critical one is the commit `"Vagrantfile: upgrade k8s to 1.7.0 for bugfixes"`.
* Vagrantfile: split out inline scripts into separate ones
* scripts: add kernel module for overlayfs
* scripts: add cni loopback plugin
* Vagrantfile: set vbguest config only if vbguest plugin is installed
* scripts: upgrade k8s to 1.7.0 for bugfixes
* kube-spawn: set the default k8s version to 1.7.0
This PR is basically a rebase of `"dongsu/devel-fix"` branch on top of the master branch. I'll update documents later when #52 got merged.
Fixes https://github.com/kinvolk/kube-spawn/issues/49

Fix bugs in Vagrantfile and init scripts

---

Vagrantfile
scripts/vagrant-mod-env.sh

In Vagrantfile, assign 2 CPUs for each VM to be able to build large source trees.
Also fix minor bugs in `vagrant-mod-env.sh`: Ignore return value of `setenforce`, as it always returns 1 if selinux is disabled. Also make sure that chmod runs only for a necessary directory k8s, instead of the whole home directory.

Vagrantfile, scripts: assign 2 CPUs and fix setup scripts

---

etc/docker_20-kubeadm-extra-args.conf
etc/kube_20-kubeadm-extra-args.conf

With runc 1.0.0-rc2 on Container Linux 1465, kube-spawn init hangs forever with message like: `"Created API client, waiting for the control plane to become ready"`. That's because docker daemon cannot execute runc, which returns error like `"no subsystem for mount"`.
See also: https://github.com/opencontainers/runc/issues/1175#issuecomment-291401577
This issue was apparently resolved in runc 1.0.0-rc3, so in theory runc 1.0.0-rc3 should work fine with Docker 17.05. Unfortunately on Container Linux, it's not trivial to replace only the runc binary with a custom one, because Container Linux makes use of torcx to provide
docker as well as runc: `/run/torcx/unpack` is sealed, read-only mounted.
As workaround, we should change cgroupdriver for docker and kubelet from systemd to cgroupfs. Then …

etc: change cgroup driver to cgroupfs

---

pkg/nspawntool/run.go

`/opt/cni/bin` needs to be mounted read-write, as additional files might need to be written into that directory inside nspawn containers.
Debugged by @iaguis

pkg/nspawntool: mount /opt/cni/bin as read-write

---

cmd/kube-spawn-runc/kube-spawn-runc.go

This avoids
```
fork/exec /run/torcx/bin/docker-runc: bad file descriptor
```
We haven't fully investigated why this happens but we don't really need
input/output for runc.

kube-spawn-runc: don't set Std{err,out,in} if we don't log

---

cmd/kube-spawn/kube-spawn.go
scripts/vagrant-mod-env.sh

Before running init, check if `overlay` kernel module is loaded, as well as if `hashsize` parameter of `nf_conntrack` is ok. Print out friendly warning if any condition is not satisfied.
Make sure `vagrant-mod-env.sh` is run as root, as it doesn't make sense anyway to run this script without root privilege.

kube-spawn: print warning for requirements before running init

---

Vagrantfile
scripts/vagrant-mod-env.sh

The git tree `go/src/github.com/kinvolk/kube-spawn` should be owned by vagrant:vagrant. Allow Vagrantfile to set it via `vm_synced_folder`. Then we don't need to run it from `vagrant-mod-env.sh`.
Also stop firewalld only if it's already started. Otherwise it could fail when firewalld is stopped.

Vagrantfile, script: let vagrant user own kube-spawn tree

---

Vagrantfile
cmd/kube-spawn/kube-spawn.go
pkg/bootstrap/node.go

Enlarge the storage pool that is actually a btrfs volume backed by `/var/lib/machines.raw`. Every btrfs volume would need more space for its metadata as much as the volume grows through CoW operations. `/var/lib/machines` should have more space than its original image size. Otherwise `/var/lib/machines` could become full when files start to be written to nspawn containers.
In short, it's equivalent to the following command sequence:
<pre>
</pre>
Unfortunately it's a temporary workaround. How much space we should add more to the image might depend on estimation during run-time operations. In the long run, systemd itself should be able to reserve more space for the storage pool, every time when it pulls an image to store in the pool.
Fixes https://github.com/kinvolk/kube-spawn/issues/66

kube-spawn: enlarge storage pool for each cloned image

---

Vagrantfile
scripts/vagrant-mod-env.sh

Support both Fedora 26, Ubuntu 17.04 (Zesty), and Debian testing. It defaults to Fedora like before.
Also update `vagrant-mod-env.sh` to support both usernames, `vagrant` and `ubuntu`.

Vagrantfile: support multiple machines

---

cmd/kube-spawn/kube-spawn.go
pkg/bootstrap/node.go
pkg/nspawntool/run.go

Ensure that the system requirements are satisfied for starting `kube-spawn`. It's just like running the commands below:
<pre>
</pre>
It was originally done by `scripts/vagrant-mod-env.sh`. However it's actually hard for end-users to take care of the requirements prior to running `kube-spawn`. So allow `kube-spawn` to do the initialization by itself a bit actively.
Also remove unnecessary warnings `"exit status 1"` while waiting on completion.
Fixes https://github.com/kinvolk/kube-spawn/issues/69

kube-spawn: ensure that system requirements are satisfied

---

scripts/bootstrap.sh

Every time when `docker.service` runs, it waits for 120 seconds doing nothing, until `systemd-networkd-wait-online.service` times out. As a result, kubeadm is being blocked until docker server became available: a huge delay for every nspawn container, although network is already online and reachable.
Let's just mask `systemd-networkd-wait-online.service`, to allow `docker.service` to run without being blocked.
Fixes https://github.com/kinvolk/kube-spawn/issues/75

scripts: mask systemd-networkd-wait-online.service

---

cmd/kube-spawn/kube-spawn.go
pkg/bootstrap/node.go

Only stopped nodes should be included in the list `nodesToRun`, which should be passed to iteration of `runNode()`. If that list is empty, just exit immediately printing out a warning.
Also rename `nodes` to `numNodes`, `NodeExists()` to `IsMachineImageExists()`,
`nodesToCreate` to `nodesToRun`.
Fixes https://github.com/kinvolk/kube-spawn/issues/82

kube-spawn: fix bug when checking for a running node

---

README.md
cmd/kube-spawn/init.go
cmd/kube-spawn/kube-spawn.go
cmd/kube-spawn/setup.go
cmd/kube-spawn/start.go
cmd/kube-spawn/stop.go
cmd/kube-spawn/up.go
scripts/vagrant-setup-env.sh

* rename command from `up` to `setup`
* split out commands into multiple files to maintain the source tree better. `init.go` for init command, `setup.go` for setup command etc.
* introduce `start` and `stop` commands. `start` wraps `machinectl pull ... coreos`, `setup` and `init`. `stop` does what `machinectl stop kube-spawn-{0,...,n}` would achieve
Fixes https://github.com/kinvolk/kube-spawn/issues/54

kube-spawn: add start/stop commands

---

pkg/cnispawn/netns.go
pkg/nspawntool/run.go
pkg/utils/utils.go

Check for availability of `$GOPATH` and `$CNI_PATH` in a flexible way. If a given path is not a valid path to a directory, fall back to the next possible path candidate. If it still fails, print out warning. That way, users could get chances to fix the paths.
Partly covers https://github.com/kinvolk/kube-spawn/issues/81

cnispawn, nspawntool: check GOPATH, CNI_PATH in a flexible way

---

Vagrantfile
cmd/kube-spawn/setup.go
pkg/bootstrap/util.go
pkg/nspawntool/run.go
pkg/utils/utils.go

Mount `.kube-spawn/default/MACHINE_NAME/mount` into `/var/lib/docker` on `MACHINE_NAME`. For example, `.kube-spawn/default/kube-spawn-0/mount` into `/var/lib/docker` on `kube-spawn-0`. Then the docker volume can be handled from rootfs on the host, and we could avoid most of storage issues.
Downside with the scenario is that rootfs on the host must be a filesystem that supports overlayfs. For example ext4 does support overlayfs, while others don't. If the host rootfs is non-supported filesystem, print out error and exit, so that users can run `"setup"` with an option `"--kube-spawn-dir=OTHER_DIR"`, where `OTHER_DIR` is ext4.
Fixes https://github.com/kinvolk/kube-spawn/issues/88

bootstrap, nspawntool: mount .kube-spawn into /var/lib/docker

---

cmd/kube-spawn/setup.go
pkg/nspawntool/run.go

Create `.kube-spawn` directory before running `PathSupportsOverlay()`, otherwise it would fail if the directory doesn't exist.
Also let the `kube-spawn --kube-spawn-dir=` take parent directory of `.kube-spawn`. For example, `"kube-spawn setup --kube-spawn-dir=/home/user"` should create a directory `"/home/user/.kube-spawn"`.
Fixes https://github.com/kinvolk/kube-spawn/issues/92

nspawntool: create .kube-spawn directory before PathSupportsOverlay()

---

cmd/kube-spawn/setup.go

As `setup` command gets usually called before `init`, we should also ensure requirements before running `setup`, to automatically load `overlay` and `nf_conntrack` modules.
Fixes https://github.com/kinvolk/kube-spawn/issues/97

kube-spawn: ensure requirements also before running setup

---

etc/weave_50-weave.network
pkg/nspawntool/run.go

Inside nspawn containers, sometimes the `weave` bridge interface becomes `DOWN` all the time, and never becomes `UP` again, no interface gets attached to the bridge. This is a known issue with systemd-networkd on Container Linux: `weave`, `vethwe-bridge`, `vethwe*` interfaces become `UP` at boot-time, but afterwards they become reconfigured by networkd again, so that `vethwe*` disappear and `vethwe-bridge` gets detached.
So we should make these interfaces `Unmanaged`, so that they cannot be reconfigured by networkd.
Fixes https://github.com/kinvolk/kube-spawn/issues/99

pkg/nspawntool: add config to unmask weave interfaces

---

cmd/kube-spawn-runc/kube-spawn-runc.go
pkg/utils/utils.go

Selectively pass Stdout/Stderr, by determining if they are terminal or not, with help of ioctl with `syscall.TCGETS`.
If we would always pass them, interactive mode of connection to containers will fail with error messages like `"container not started"`. If we would not pass them at all, then `"kubectl logs"` would not be able to print any logs.
Suggested by @iaguis
Supersedes https://github.com/kinvolk/kube-spawn/pull/98

kube-spawn-runc: selectively pass Stdout/Stderr before running command

---

README.md
pkg/bootstrap/util.go
pkg/nspawntool/run.go

Now that kube-spawn automatically creates `.kube-spawn` under `$PWD`, we should move `tmp` directory to `.kube-spawn/default`.
Change documents as well to recommend using `$KUBECONFIG` instead of long command-line options.
See also https://github.com/kinvolk/kube-spawn/pull/96#discussion_r129821464

pkg/nspawntool: move tmp directory into .kube-spawn

---

cmd/kube-spawn/setup.go
pkg/bootstrap/kubernetes.go
pkg/nspawntool/run.go

To be able to make kubelet's port-forward work, download static binary of `socat` to be installed under `/opt/bin/`.
This is workaround for now. In the future we need to find a proper solution for the issue.
Fixes https://github.com/kinvolk/kube-spawn/issues/105

kube-spawn, bootstrap: include static binary of socat in containers

---

doc/troubleshooting.md
pkg/bootstrap/node.go
scripts/vagrant-mod-env.sh

Instead of stop firewall, we need to just allow traffic through CNI network interface `cni0`.
Also set the default policy of `FORWARD` chain to `ACCEPT`.
Though as for SELinux, we should automatically turn off the enforcing mode, as there's no way around multiple issues.
Fixes https://github.com/kinvolk/kube-spawn/issues/76

pkg/bootstrap: allow CNI traffic, disable SELinux enforcing mode

---

cmd/kube-spawn/setup.go
pkg/bootstrap/node.go
pkg/bootstrap/util.go

Before enlarging storage volume, we should first check if the additional volume size would make the whole storage volume full. If that might be the case, we should not enlarge the volume, and print warning to users.
Possibly resolves https://github.com/kinvolk/kube-spawn/issues/85

pkg/bootstrap: check if there's enough space in storage volume

---

cmd/kube-spawn-runc/kube-spawn-runc.go
cmd/kube-spawn/init.go
cmd/kube-spawn/kube-spawn.go
pkg/utils/utils.go

Print args only when `logPath` (`$KUBE_SPAWN_RUNC_LOG_PATH`) is explicitly set. Otherwise the logs will appear at the top of every pod's log.
At the end of init command, print out message for setting `$KUBECONFIG` based on real lookups: first try `$PWD/.kube-spawn/default/kubeconfig`, then `$GOPATH/src/github.com/kinvolk/kube-spawn/.kube-spawn/default/kubeconfig`, then `$HOME/go/src/github.com/kinvolk/kube-spawn/.kube-spawn/default/kubeconfig`.
Fixes https://github.com/kinvolk/kube-spawn/issues/104 https://github.com/kinvolk/kube-spawn/issues/111

Fix message for kubeconfig, only log for runc when necessary

---

README.md

I've updated the README to include a running demo and to highlight the easy, one-liner `up` command over the 3 stage cluster bring-up.

Update readme with demo and use the `up` command

---

Makefile

On vagrant I'm getting:
```
[vagrant@fedora26-vbox ~]$ ./build.sh 
+ cd /home/vagrant/go/src/github.com/kinvolk/kube-spawn
+ go get -u github.com/containernetworking/plugins/plugins/...
+ make vendor all
which: no dep in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin:/home/vagrant/go/bin:/usr/local/go/bin)
dep ensure
make: dep: Command not found
make: *** [Makefile:15: vendor] Error 127
```
The `dep` binary is not installed, changing the go get path to `github.com/golang/dep/cmd/dep` fixes it.
Cheers,

fix go get command for dep

---

cmd/kube-spawn/init.go
cmd/kube-spawn/setup.go
etc/kube_20-kubeadm-extra-args-k8s18.conf
etc/kube_tmpfiles_kubelet.conf
etc/kubeadm.yml
pkg/bootstrap/node.go
pkg/distribution/registry.go
pkg/nspawntool/kubeadm.go
pkg/nspawntool/run.go
pkg/utils/utils.go
scripts/init.sh

As the `k8srelease` can be either `"dev"` or `""` in case of development version of K8s, we should check for both `k8srelease != ""` and  `k8srelease != "dev"`. Move the existing helper `isDev()` to `utils.IsK8sDev()` to make it usable from nspawntool too.
Fix URL for gcr.io as the registry `gcr.io` has changed its prefix to `google-containers`.
Reported & debugged by @iaguis

Fix a check for k8srelease and URL for gcr.io

---

.gitignore
Gopkg.lock

Update `Gopkg.lock` to sync with `Gopkg.toml`, by running `dep ensure` to regenerate inputs-digest to avoid warnings like:
```
$ dep status
Lock inputs-digest mismatch. This happens when Gopkg.toml is modified.
Run `dep ensure` to regenerate the inputs-digest.
```
Also update `.gitignore` to include more unnecessary files.

Update Gopkg.lock and .gitignore

---

cmd/kube-spawn/up.go
pkg/bootstrap/node.go

As kube-spawn needs Container Linux 1478.0.0 or newer, we need to check for the version.
If the version is too low, it fails and recommends users to remove the old local image, so that the next run of `kube-spawn` will download a new image automatically.
Fixes https://github.com/kinvolk/kube-spawn/issues/114

pkg/bootstrap: check for Container Linux version

---

.gitignore
Makefile

Brace expansion doesn't work with all shells.
`rootfs.tar.xz` etc. is from the past and not used anymore.

Cleanup and update `Makefile` and `gitignore`

---

README.md
doc/troubleshooting.md
pkg/bootstrap/node.go

The name of the machine given to machinectl (e.g. kube-spawn-0) is also
used to set the cgroup path. Example:
/machine.slice/machine-kube\x2dspawn\x2d0.scope
Having dashes make things more complicated because they are escaped by
systemd to '\x2d' in the cgroup path.
When adding the support for cgroup-per-qos in kube-spawn, we will need
to pass the parameter --cgroup-root= to the Kubelet. With the '\x2d'
escape sequence, we have now a backslash. That would need to be escaped
when writing the kubelet service file.
So instead of over-complicating things with a double-escaping sequence,
let's just get rid of the dashes.
-----
Related topics:
- https://github.com/kinvolk/kube-spawn/issues/12#issuecomment-331495622
- https://github.com/kubernetes-incubator/rktlet/pull/124

kube-spawn machine naming: use kubespawn%d without dashes

---

pkg/bootstrap/kubernetes.go
pkg/nspawntool/binds.go

Its name was changed recently. Switch to a commit to avoid this kind of
issues in the future. Same for the socat repo.

Fix k8sGithubURL and kubeadm config file name

---

cmd/kube-spawn/setup.go

For the ContainerRuntime parameter of `bootstrap.sh`, we need to pass an explicit string, either `rktlet` or `docker`. Without this fix, bootstrap.sh will silently fail in case of rkt, because there's no `rkt.service` to enable. As a result, the rest of commands in bootstrap.sh will not run at all.
Also fix a bug to pass `--fail-swap-on=false` for k8s 1.8. The kubelet option `--fail-swap-on=false` is needed not only by `dev` version, but also by k8s release 1.8.0 or newer. Without the fix, k8s 1.8 will not run at all.
Reported by @iaguis

Fix bugs in setting up k8s parameters

---

README.md

Seems kube-spawn up command doesn't create configuration in the current
directory but rather on the system at /var/lib/kube-spawn/default.

doc: Update location of configuration

---

README.md

Otherwise, you get a very unfriendly error:
error: error converting YAML to JSON: yaml: line 328: mapping values are not allowed in this context

docs: Specify URL to raw YAML rather than webpage

---

doc/rktlet.md
doc/troubleshooting.md

Describe about kubernetes version issues in `doc/troubleshooting.md`.
Also move from the token issue from `rktlet.md` to `troubleshooting.md`, as it's not exactly a rkt-specific issue.

doc: recommend using k8s 1.7.3 or newer

---

pkg/nspawntool/binds.go

Instead of hardcoding "stage1-coreos.aci".

nspawntool: use stage1 filename

---

Vagrantfile

vagrant-libvirt plugin allows to run vagrant VMs by libvirt, using KVM as a hypervisor. That change also required to use Fedora box compatible both with virtualbox and libvirt providers.

vagrant: Add vagrant-libvirt support

---

README.md

The tool is named kube-spawn, not kube-nspawn.

doc: Fix a typo

---

scripts/vagrant-setup-env.sh

This commit ensures that KUBECONFIG is set as part of `vagrant up`.

Add KUBECONFIG to env

---

cmd/kube-spawn/start.go
pkg/bootstrap/node.go

We should not resize the storage pool, if the pool image `/var/lib/machines.raw` does not exist. In that case, it's just fine to ignore resizing the image, because it means that systemd-machined did not have to create an image to be loopback mounted.
Fixes https://github.com/kinvolk/kube-spawn/issues/170

cmd/kube-spawn: ignore resizing storage pool if the pool image does not exist

---

pkg/nspawntool/run.go

The command `start` panics with `index out of range`, when the number specified in the `node` variable in `kspawn.toml` is greater than the actual number of nodes.
To avoid the panic, we should check for the actual length of the slice of nodes.
Fixes https://github.com/kinvolk/kube-spawn/issues/183

pkg/nspawntool: fix panic when running more nodes than defined

---

cmd/kube-spawn/create.go

We need to call `EnsureRequirements` before `PathSupportsOverlay`.
Otherwise in case of the kernel module `overlay` missing, `PathSupportsOverlay` just fails because it reports that the underlying filesystem does not support overlayfs. It can be simply solved by loading the kernel module before calling it.

cmd/kube-spawn: ensure requirements before PathSupportsOverlay

---

cmd/kube-spawn/destroy.go
pkg/bootstrap/cninet.go

Let's make `./kube-spawn destroy` removes every CNI configuration file under `/var/lib/cni/networks/kube-spawn-net` as well as `/etc/cni/net.d/10-kube-spawn-net.conf`.
Fixes https://github.com/kinvolk/kube-spawn/issues/11

cmd/kube-spawn: remove cni config when destroying a cluster

---

cmd/kube-spawn/start.go
pkg/bootstrap/scripts.go
pkg/config/defaults.go
pkg/config/utils.go

Machines and their images in `/var/lib/machines` get a name like:  
`kubespawndefault0`, `default` becomes the cluster name
Fixes #187

Fix colliding machine names when running multiple clusters

---

pkg/bootstrap/util.go

As moby does not allow ecryptfs to be used as underlying filesystem of overlayfs, we should also check for ecryptfs in `PathSupportsOverlay()` to prevent ecryptfs from being used.
Fixes https://github.com/kinvolk/kube-spawn/issues/126

pkg/bootstrap: check also for ecryptfs under overlayfs

---

pkg/bootstrap/bridge.go
pkg/cnispawn/netns.go
pkg/cnispawn/spawn.go
pkg/nspawntool/run.go

This is mostly about looking for the binary in `PATH` too, instead of expecting them to be in the current working directory.
Fixes #198.

Fix some fork/exec issues.

---

pkg/nspawntool/run.go

Testing on Ubuntu 17.10 on GCE with only 2 vCPUs, `kube-spawn start` fails by timeout:
```
failed to start machine: timeout waiting for "kubespawndefault2" to start
not all machines started
```
I couldn't get it to pass this step without increasing the timeout.

start: increase timeout

---

pkg/bootstrap/bridge.go
pkg/nspawntool/run.go
pkg/utils/command.go

`exec.Command` was not actually falling back to executing binaries in current working directory but it was setting an internal error which was returned at the time `cmd.Start` was called.
These two commits fixes that, so kube-spawn prefers to execute the binaries in current working directory if they exist and falls back to searching `PATH` for them.

Some fixes for #198

---

pkg/bootstrap/node.go
pkg/bootstrap/util.go
pkg/script/kubeadm-extra-runtime.go
pkg/utils/kubernetes.go

Clean up unused functions except for `CheckValidFile` which will be probably used later again.
These are detected by `codecoroner funcs --ignore vendor ./...`.

pkg: clean up unused functions

---

pkg/bootstrap/node.go

'create' fails because it attemps to use the CNI configuration file
before it is created.
Symptoms:
```
$ sudo -E ./kube-spawn create --nodes=3
creating cluster environment "default"
spawning kubernetes version "v1.7.5"
pulling coreos image...
ensuring environment
2017/11/12 14:48:31 open /etc/cni/net.d/10-kube-spawn-net.conf: no such file or directory
error checking CNI bridge: exit status 1
```
Fixes https://github.com/kinvolk/kube-spawn/issues/206

cni config: create config before using it

---

doc/devel/release.md

Fixes https://github.com/kinvolk/kube-spawn/issues/195
-----
It mostly comes from the [rkt release guide](https://github.com/rkt/rkt/blob/master/Documentation/devel/release.md). I removed the signature since we are not ready for signing yet. I added documentation for the CNCF conformance tests.

devel doc: how to do a release

---

pkg/bootstrap/node.go

When running `machinectl pull-raw`, we need to set Stdout to os.Stdout, as well as Stderr to os.Stderr, to get useful output messages printed on the screen. So far only a simple message "pulling coreos image..." has been printed. With this change, we can have precise messages like that:
```
Pulling 'https://alpha.release.core-os.net/amd64-usr/current/coreos_developer_container.bin.bz2',
Saving as 'coreos'.
```
Partly covers https://github.com/kinvolk/kube-spawn/issues/205

pkg/bootstrap: turn on stdout/err when pulling an image

---

README.md

Since https://github.com/kinvolk/kube-spawn/pull/199, it is possible to install kube-spawn binaries under a system directory.
Fixes https://github.com/kinvolk/kube-spawn/issues/203

README: add an instruction to install binaries

---

cmd/kube-spawn/stop.go

Sometimes `kube-spawn stop` succeeded, but afterwards kube-spawn is not able to remove `kubespawndefault*` images, because of errors like `device or resource busy`. That makes the next round of starting clusters fail because of the remaining images.
This happens simply because it takes some time until nspawn containers can release every resource. So we need to retry to remove image until it succeeds, up to 15 * 0.5 sec = 7.5 sec.
Fixes https://github.com/kinvolk/kube-spawn/issues/213

cmd/kube-spawn: retry to remove image until it succeeds

---

Vagrantfile
doc/distro.md
scripts/vagrant-mod-env.sh
scripts/vagrant-setup-env.sh

In Vagrantfile, do not install Kubernetes and docker. On the testing host machine, we don't necessarily need to install Kubernetes and docker. Kubernetes binaries are downloaded anyway under `/var/lib/kube-spawn`, and docker isn't used at all.
Also upgrade Ubuntu to 17.10 (Artful), and disable the stub resolver of systemd-resolved to avoid DNS resolving issues inside nspawn containers.

Optimize Vagrantfile, support Ubuntu 17.10

---

scripts/vagrant-mod-env.sh

kube-spawn vagrant environment does not use
docker anymore for builds. This commit removes
all the leftovers after docker in vagrant provision
script.

Remove leftovers after docker removal

---

pkg/nspawntool/kubeadm.go

kubeadm got a new option in version 1.8: `--discovery-token-unsafe-skip-ca-verification`
See: https://github.com/kubernetes/kubernetes/pull/49520
Since version 1.9, it became mandatory to either use it to skip verification, or to use `--discovery-token-ca-cert-hash=...`
See: https://github.com/kubernetes/kubernetes/pull/55468
Since kube-spawn is a developer tool used on one physical machine, use the former.

kubeadm join: fix TLS on Kubernetes >=1.9

---

README.md
cmd/kube-spawn/create.go
cmd/kube-spawn/start.go
doc/dev-workflow.md
pkg/bootstrap/scripts.go
pkg/config/types.go
pkg/distribution/registry.go
pkg/nspawntool/kubeadm.go
pkg/script/kubeadm-config.go

Add `--hyperkube-tag` (or `-t`) on `kube-spawn create` to specify which hyperkube Docker image to use. This is useful to compile different versions of Kubernetes and test them in parallel. `doc/dev-workflow.md` explains in more details how to use it.
kube-spawn will start a `registry` container and push the hyperkube image there under the name `10.22.0.1:5000/hyperkube-amd64:$TAG`. Then, kubeadm will pick that image.
Use the `unifiedControlPlaneImage` option in the kubeadm configuration file (>= 1.8) in addition to the old environment variable `$KUBE_HYPERKUBE_IMAGE` (< 1.8). This means `--dev` cannot be used anymore on 1.7 branches, but the 1.7 releases still work so it should not be a problem.
The dev workflow is now documented in doc/dev-workflow.md
Fixes …

Fix dev workflow

---

doc/troubleshooting.md

This happens when trying to run many nodes.
Also, add a TOC so users have an overview of the problems addressed.

 doc/troubleshooting: how to trouble shoot inotify problems 

---

cmd/kube-spawn/start.go
pkg/utils/kubernetes.go

This help message for setting `$KUBECONFIG` at the end of `kube-spawn start` used to exist, but it was removed by https://github.com/kinvolk/kube-spawn/pull/161.
We should bring it back for better user experience.
Fixes https://github.com/kinvolk/kube-spawn/issues/230

cmd/kube-spawn: bring back help message for KUBECONFIG

---

cmd/kube-spawn/stop.go

We should make sure we end up in a state where the cluster can be
started again, so we remove images and clear cluster configuration even
if there's no running machines.

stop: remove images even if there's no machines to stop

---

pkg/config/types.go

We need to define a toml attribute "dir" for kube-spawn-dir, to be able to make use of a global option `-d' (or `--dir'). Otherwise the dir string is not stored in `kspawn.toml` at all, and as a result, the custom directory name cannot be set.
Fixes https://github.com/kinvolk/kube-spawn/issues/238

pkg/config: fix a bug with kube-spawn-dir in kspawn.toml

---

cmd/kube-spawn/create.go
cmd/kube-spawn/destroy.go
cmd/kube-spawn/list.go
cmd/kube-spawn/restart.go
cmd/kube-spawn/start.go
cmd/kube-spawn/stop.go
cmd/kube-spawn/up.go

Kube-spawn's commands are meant to run without any arguments, as all the necessary parameters are set via individual options, e.g. `-c` for cluster name, `--kubernetes-version` for the cluster's k8s version, etc. When a user happens to type in unnecessary parameters without an option string, e.g. `kube-spawn destroy mycluster`, then it could result in
unexpected behavior like destroying the `default` cluster, because the cluster name defaults to `default` when there's no '-c' option given.
So we should check for the number of arguments, and fail immediately when any unnecessary argument is given from the command line. Then users can simply react to that by typing a new command with correct options.
Fixes https://github.com/kinvolk/kube-spawn/issues/236

cmd: fail when unnecessary parameters are given

---

cmd/kube-spawn/start.go
pkg/utils/kubernetes.go

Now that kube-spawn is able to deal with multiple clusters, path to kubeconfig, `$KUBECONFIG`, can also differ depending on the cluster name. So `utils.GetValidKubeConfig()` should take a parameter for the cluster name, to compose path to kubeconfig correctly. For example, if the cluster's name is `mycluster`, KUBECONFIG will be `/var/lib/kube-spawn/mycluster/kubeconfig`.
Fixes https://github.com/kinvolk/kube-spawn/issues/230

pkg/utils: figure out kubeconfig path correctly with a cluster name

---

Vagrantfile
doc/vagrant.md
scripts/vagrant-setup-env.sh
vagrant-all.sh
vagrant-fetch-kubeconfig.sh

Introduce the KUBESPAWN_REDIRECT_TRAFFIC environment
variable to the build.sh script which redirects the
traffic incoming to the 6443 port in Vagrant VM to
the nspawn container with kube-apiserver.
Fixes #217

vagrant: Expose apiserver outside the VM

---

cmd/kube-spawn/create.go
cmd/kube-spawn/destroy.go
cmd/kube-spawn/restart.go
cmd/kube-spawn/start.go
cmd/kube-spawn/stop.go
cmd/kube-spawn/up.go

Ordinary commands, create, destroy, restart, start, stop, and up, need to run with root privileges. So we need to exit if euid is not 0.
Though we need to exclude the list command, as non-root users are able to read profiles.
Fixes https://github.com/kinvolk/kube-spawn/issues/231

cmd/kube-spawn: abort if it's non-root user

---

cmd/kube-spawn/kube-spawn.go

If not explicitly disabled, cobra prints errors in `cmd.Execute`, i.e.
no need to log it a second time.
https://github.com/spf13/cobra/blob/ccaecb155a2177302cb56cae929251a256d0f646/command.go#L842-L844

kube-spawn: don't double print errors

---

pkg/config/defaults.go

kube-spawn allows users to configure the container runtime with
`--container-runtime` (e.g. `--container-runtime=rkt`) but doesn't
actually make sure the passed value is known/supported and instead
continues with the setup process until it fails at a later stage. Error
out early.

Error out when unknown container runtime is set

---

pkg/bootstrap/node.go

`IsConntrackHashsizeCorrect()` is expected to return true, when the value of `/sys/module/nf_conntrack/hashsize` * 4 is less than the value of `/proc/sys/net/nf_conntrack_max`. However so far the string parsing logic has had a bug that the value obtained from the procfs or sysfs is passed without trimming whilespaces. As input string is usually given
such as `16384\n`, with a trailing newline character, `strconv.Atoi()` fails because of the newline. Then both `hs` and `ctmax` become 0, and `IsConntrackHashsizeCorrect()` returns always true. Obviously there will be no chance of adjusting the hashsize correctly as expected.
So we need to apply `strings.Trimspace()` for each input string. Then the newline character will be gone, and `IsConntrackHashsizeCorrect()` will work as expected.
Fixes …

pkg/bootstrap: fix a bug when parsing kernel parameters

---

Dockerfile.build

For better build speed, we should use golang docker image instead of fedora, because we don't actually need the whole distro just for building go binaries.
Comparison of build duration, including fetching remote docker images:
* previously with fedora 27:   143.964 sec
* currently with golang latest: 74.608 sec

Dockerfile: build kube-spawn based on golang image instead of fedora

---

pkg/bootstrap/util.go

We check the availability of the overlay kernel module by basically
grepping the contents of `/proc/filesystems` for `overlay`. The check
will fail, if the overlay module wasn't loaded. So let's try to load
the module before checking the `/proc/filesystems` contents.
Normally the proper way for checking the availability of the overlay
kernel module would be to mount a directory with overlayfs
filesystem. At this point, the overlay kernel module would be
automatically loaded and the mount would happen. If the module were
not available, we would get an error. But the problem is that we don't
actually mount anything - it is done by systemd-nspawn. So I guess
that for the sake of a better error reporting and a better cleanup of
a failed state, we don't go that way.

Fix the check for overlayfs

---

cmd/kube-spawn/create.go
pkg/bootstrap/node.go
pkg/cluster/cluster.go
pkg/nspawntool/run.go

As the base image, we support [Flatcar Linux](https://flatcar-linux.org) images instead of CoreOS Container Linux images.
We replace hard-coded values "coreos" with a proper image name. Let's just remove the `--machinectl-image` option to make it simple.

cmd, pkg/bootstrap: support Flatcar Linux as base image

---

pkg/cluster/cluster.go
pkg/cluster/clusterfiles.go

When starting a kube-spawn cluster with kubeadm 1.11 or newer, `kube-spawn start` hangs forever during the bootstrap phase. It's because kubeadm 1.11 or newer asks users to type Y or n, while our bootstrap script runs only `kubeadm reset`. It works fine when running with
`kubeadm reset --force`, which breaks kubeadm 1.10 or older, because the lower versions don't support `--force`.
Fix the bug by dealing with kubeadm reset options differently when the kubeadm version is 1.11 or newer.
Fixes https://github.com/kinvolk/kube-spawn/issues/278

pkg/cluster: fix bug when starting cluster with kubeadm >= 1.11

---

doc/distro.md
scripts/vagrant-setup-env.sh
vendor/github.com/docker/docker/hack/make/.build-deb/docker-engine.docker.default
vendor/github.com/docker/docker/hack/make/.build-deb/docker-engine.docker.init
vendor/github.com/docker/docker/hack/make/.build-deb/docker-engine.docker.upstart
vendor/github.com/docker/docker/hack/make/.build-deb/docker-engine.udev
vendor/github.com/docker/docker/project/CONTRIBUTORS.md

* Move the `--nodes` option to `start` command, as `create` does not  have the option any more.
* Use `--cni-plugin-dir` instead of an env variable
* Fix `$KUBECONFIG` to `/var/lib/kube-spawn/clusters/default/admin.kubeconfig`
* Replace coreos with flatcar
Fixes https://github.com/kinvolk/kube-spawn/issues/289

scripts: fix vagrant setup script to make it up-to-date

---

README.md
doc/troubleshooting.md
pkg/cluster/cluster.go

While working on 924bb3b41a4126a4c89e4be8779ac014f0d41151 I did not
re-add the `EnlargeStoragePool` invocation and first time users
encountered disk space issues more often again ever since.
Also, add a note to the README and troubleshooting document to tell
users what to do.
Partly covers #281

Re-add `EnlargeStoragePool` invocation

---

README.md
cmd/kube-spawn/create.go
cmd/kube-spawn/start.go
pkg/cluster/cluster.go
pkg/cluster/clusterfiles.go

Default remains weave. User can now set --cni-model [weave|flannel|calico]
on create. For flannel and calico one must also set pod-network-cidr
(as per https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/).
Add ability to set cluster-cidr.

Add support for flannel and calico.

---

README.md
pkg/bootstrap/node.go

This regression broke my ability to run (since /var/lib/machines is mounted on a real partition, not loopback).
Commit message has the bulk of the rationale.
Also correct missing error handling.

Correct resize /var/lib/machines logic

---

pkg/bootstrap/node.go
pkg/bootstrap/util.go
pkg/cluster/cluster.go

Most error checking was missing from pkg/bootstrap/node.go.
Added to all utility functions.
In addition, pkg/bootstrap/node.go made assumptions about
host-path for binaries (machinectl/qemu-img/mount etc). Remove this.
If the binaries are not on the PATH, fail. This is the reason
for Unix PATH, to indicate where to find executables, hard-coding
fallbacks can create a security issue or astonishment.
The code had a hard-coded assumption that the machine had
selinux available (e.g. it assumed selinux is enforcing/not-enforcing)
where there is a 3rd-option (not available). If selinux is not
available (e.g. Ubuntu-derived hosts), then return false
from isSELinuxEnforcing().

Add error handling to utility functions, remove assumptions about host

---

pkg/bootstrap/node.go

Statfs needs to multiply Bsize * Blocks to get size of /var/lib/machines. This was missing.

Statfs needs to multiply Bsize * Blocks to get size of /var/lib/machines

---

pkg/bootstrap/node.go

If the storage pool is not initialized at all, the storage pool could be only 500MB by default, which is way smaller than the default image size of Flatcar Linux, 1.6G.
So we need to resize the pool to around 2G, even before pulling the base image.

pkg/bootstrap: enlarge pool size also before pulling base image

---

pkg/cluster/clusterfiles.go
pkg/nspawntool/run.go

The /var/lib/kubelet directory is used to store the emptyDir
volumes of the various Pods. The worker container has < 1GB of
space free, insufficient. Change /var/lib/kublet to be
a bind-mount of the host.
Kubeadm reset removes the /var/lib/kubelet directory (which
is our bind-mount). However, kubeadm reset is not required
since the image starts up fresh, so remove it.
Resolves https://github.com/kinvolk/kube-spawn/issues/309

Put /var/lib/kubelet onto host as bind-mount rather than in container.

---

cmd/kube-spawn/up.go

Otherwise it would be empty and `kubespawn up` would fail.

cmd/up: add --cni-plugin flag

---

.travis.yml
Vagrantfile

Upgrade go from 1.9 to 1.11.
(Note, golangci needs to be `latest`, as there's no 1.11 yet.)
Upgrade Fedora from 26 to 28, Ubuntu from 17.10 to 18.04.
Install make before building kube-spawn.

travis, Vagrantfile: upgrade Go, Fedora, Ubuntu

---

pkg/cluster/cluster.go
pkg/cluster/clusterfiles.go

Calico is capable of enabling ipv4+ipv6 dual stack usage, but only if it has an ipv6 range in ipam. Without the ipv6 range, even lo is not bound to a v6 address, preventing code which explicitly wants to use v6 even locally (e.g. unit tests) from operating.
Add in an explicit v6 range (from the the unique local address range of fc00::/7). Do this by mirroring the config file from
https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation /hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
into the system, with the change. The ipv4 section of the ipam is configured to match Calico's felix expectation.

Enable ipv4/ipv6 dual-stack in Calico.

---

pkg/cluster/cluster.go
pkg/cluster/clusterfiles.go

Since k8s v1.11, API version of kubeadm has changed to `v1alpha2`, and `v1alpha1` is deprecated. So it's recommended to use `v1alpha2` for kubeadm >= 1.11, and `v1alpha1` will be completely removed in the upcoming release 1.12.
We need to introduce a new option for the API version, to conditionally deal with it.
Fixes https://github.com/kinvolk/kube-spawn/issues/280

pkg/cluster: change API to v1alpha2 for kubeadm >= 1.11

---

pkg/bootstrap/download.go
pkg/utils/hash.go

Downloaded k8s binary files, e.g. `kubectl`, sometimes can be corrupted, due to many reasons, like intermittent network errors. The thing is, in this case kube-spawn simply continues to start clusters with the broken files, and actually tries to run those. It obviously fails, but the failures are not directly visible to users, so users need to get into one of the containers to debug the issues. For most users it's quite hard.
To fix that, we should verify if each downloaded Kubernetes binary file is valid, with help of the given sha1 hash file, i.e. `filename+".sha1"`. (Unfortunately on dl.k8s.io, there's no other hash file available, no sha256 at all) If the hash is not correct, simply error out to inform users that something is wrong with the files.
For example, it does the same job as …

pkg/bootstrap: verify hash of each k8s binary file

---

pkg/cluster/clusterfiles.go

Starting from kubeadm v1.12.0, both `kind` and `apiVersion` are necessary in the kubeadm config file when initializing the cluster. If `kind` is missing, `kubeadm init` simply fails like this:
```
master-ajk8ix invalid configuration: kind and apiVersion is mandatory information that needs to be specified in all YAML documents
Failed to start cluster ...
```

pkg/cluster: add kind field in the kubeadm config option

---

pkg/cnispawn/spawn.go

This resolves part of the issue referenced in
[#326](https://github.com/kinvolk/kube-spawn/issues/326) needed to run
privileged pods. However, I don't believe it is sufficient to fully
support a Pod which wants to run e.g. Docker-In-Docker.
Signed-off-by: Don Bowman <db@donbowman.ca>

Enable keyring and bind-mount /sys/kernel/security for privileged operation

---

pkg/cnispawn/spawn.go
pkg/nspawntool/run.go

Starting from systemd v239, it's no more possible to create device nodes inside systemd-nspawn containers, because systemd-nspawn creates subcgroups for each machine slice under `/sys/fs/cgroup/devices`.
To make docker containers inside nspawn containers capable of creating devices, we need to do workaround. Let's pass `--keep-unit` to systemd-nspawn, and call `systemd-run --scope` for using the cni-spawn wrapper. Then the transient scope gets created with a proper `DevicePolicy` property for each invocation, printing out the CNI result to stdout like before. That way, we can avoid dealing with additional unit files to allow device creation.
Fixes https://github.com/kinvolk/kube-spawn/issues/324

pkg/nspawntool: use transient scope to fix device cgroups issues

---

cmd/kube-spawn/create.go
cmd/kube-spawn/up.go
pkg/cluster/cluster.go
pkg/cluster/clusterfiles.go

Let's bump the default Kubernetes version to v1.12.3, the most secure up-to-date version. This is mostly because of the critical security issue https://github.com/kubernetes/kubernetes/issues/71411.
Apply CNI plugins outside of nspawn containers. Starting from k8s v1.13, the insecure port 8080 of kube-apiserver is not available any more, as it has been deprecated. So we cannot run `kubectl apply` inside of nspawn containers.
Kubeadm v1.13 or newer should run with a config with `apiVersion: v1beta1`. In case of apiVersion `v1alpha*`, the `InitConfiguration` part can contain `apiServerExtraArgs`, `authorizationMode`, and `controllerManagerExtraArgs`. However, in case of apiVersion  `v1beta*`, these option should be removed or moved into each corresponding part. Otherwise kubeadm would …

Fix issues for running with k8s v1.13

---

pkg/cluster/cluster.go

The `host-device` plugin is not included in the CNI plugins v0.6.0, it's available starting from v0.7.0. Actually kube-spawn does not need the plugin to spawn the cluster.
Let's simply remove it from the required CNI plugins list.
Fixes https://github.com/kinvolk/kube-spawn/issues/334

pkg/cluster: do not require host-device CNI plugin

---

pkg/cluster/cluster.go

There has been a critical issue in kube-spawn with weave 2.0.5. Inside nspawn clusters, `veth*` interfaces are not created at all. As a result, coredns pods cannot start at all, and k8s nodes do not become ready at all. Apparently the yaml file provided by weave 2.0.5 is not compatible with the current k8s versions.
Let's upgrade it to 2.5.1, which seems to work fine.

pkg/cluster: upgrade weave to 2.5.1 to fix veth interface issue

---

cmd/kube-spawn/start.go
pkg/bootstrap/node.go
pkg/cluster/cluster.go

Allow users to specify a certain channel name, like `alpha`, `beta`, or `stable`, when starting a cluster.
```
./kube-spawn start --flatcar-channel=beta
```
Note, we don't necessarily enforce one of the 3 channel names, because Flatcar could have other channel names in the future. When a wrong channel name is given, machinectl will anyway fail due to a wrong URL.
Fixes https://github.com/kinvolk/kube-spawn/issues/272

cmd, pkg: allow for specifying an arbitrary flatcar channel

---

pkg/cluster/cluster.go

When applying CNI plugins to nspawn containers, we have to apply the CNI config from the host, specifying the cluster's rootfs, like `/var/lib/kube-spawn/clusters/default/rootfs-base-readonly/etc/cni`.
So far the path has not been set correctly, like `/etc/cni`. Since calico was the only CNI plugin that reads config from the local rootfs, the bug affected only calico, not the other CNI plugins.
This bug was introduced by https://github.com/kinvolk/kube-spawn/pull/332, when we had to fix issues caused by changes from recent kubeadm versions. It was a necessary change, but the change caused the regression.
Fixes https://github.com/kinvolk/kube-spawn/issues/337

pkg/cluster: fix path to the CNI config directory for Calico

---

pkg/cluster/cluster.go

CNI plugins 0.8.0 does not ship sample plugin anymore. It has been removed in
https://github.com/containernetworking/plugins/pull/295, so we shouldn't
attempt to copy it.
Closes #341

pkg/cluster: don't copy 'sample' CNI plugin
