README.md

README: Fix several typos and sentences

---

README.md

- use sudo for some commands
- add dependencies details

README: updates

---

Makefile

Do not update vendor on every `make`

---

cmd/cnispawn/cnispawn.go
pkg/cnispawn/spawn.go
pkg/nspawntool/run.go

This PR is in preparation for the move to container linux as default base image for the nodes.

Expose nspawn options in cnispawn

---

Makefile
cmd/kubeadm-nspawn/kubeadm-nspawn.go

Add version flag

---

README.md
cmd/kubeadm-nspawn/kubeadm-nspawn.go
pkg/bootstrap/cninet.go
pkg/cnispawn/netns.go
pkg/nspawntool/run.go

Also updates the code according to upstream changes
Closes #43

Write cni config to /etc/cni/net.d

---

cmd/kubeadm-nspawn/kubeadm-nspawn.go

Fix usage of bootstrap.WriteCNIConf()

---

Makefile
README.md
Vagrantfile
cmd/cni-noop/cni-noop.go
cmd/cnispawn/cnispawn.go
cmd/kube-spawn-runc/kube-spawn-runc.go
cmd/kube-spawn/kube-spawn.go
etc/daemon.json
glide.yaml
pkg/bootstrap/cninet.go
pkg/bootstrap/node.go
pkg/cnispawn/netns.go
pkg/nspawntool/bootstrap.go
pkg/nspawntool/kubeadm.go
pkg/nspawntool/run.go
scripts/init-release.sh
scripts/init.sh
scripts/join-release.sh
scripts/join.sh

Rename to kube-spawn

---

cmd/kube-spawn/setup.go

Only stopped nodes should be included in the list `nodesToRun`, which should be passed to iteration of `runNode()`. If that list is empty, just exit immediately printing out a warning.
This was originally fixed via https://github.com/kinvolk/kube-spawn/pull/83, but later the fix got lost during rebase. So let's fix it again.

kube-spawn: fix bug when checking for a running node (v2)

---

README.md
scripts/vagrant-setup-env.sh

Install all CNI plugins

---

pkg/bootstrap/node.go

So far only systemd v232 or newer has been supported. One of the reasons is `GetRunningNodes()` being unable to parse output of `"machinectl list"`.
For example, for systemd v232 or newer:
<pre>
kube-spawn-0 container systemd-nspawn coreos 1478.0.0 10.22.0.130...
</pre>
OTOH systemd v231 or older:
<pre>
kube-spawn-0 container systemd-nspawn
</pre>
Let's improve parsing mechanism of `GetRunningNodes()` to support the legacy format of systemd v231 or older.

pkg/bootstrap: improve mechanism of GetRunningNodes()

---

README.md
doc/troubleshooting.md
doc/vagrant.md

Describe more about troubleshooting tips, mainly about setting up nodes as well as requirements. Fix typos and change names too.
Closes https://github.com/kinvolk/kube-spawn/issues/81

doc: describe more about troubleshooting tips

---

pkg/nspawntool/run.go

Rewrite `RunNode()` in nspawntool to check errors in a structured way.
* Introduce a structure `bindOption` that represents a single bind option string, e.g. `--bind=/src/file:/dst/file`. Each instance has 3 entries, `bindPrefix`, `srcMount`, and `dstMount`, which would be `--bind=`, `/src/file`, and `/dst/file` repectively in the example.
* Initially a list of bind options is composed of type `[]bindOption`, which will be afterwards transformed into `[]string` that can be directly passed to systemd-nspawn. Those conversions are done by `buildDefaultBindsList()` as well as `buildK8sBindsList()`.
* For each `srcMount`, check if the path exists. If not, error out. This is necessary for avoiding such cases where systemd-nspawn gets stuck suddenly without printing any error, whenever a …

pkg/nspawntool: rewrite nspawntool to validate srcdir

---

scripts/init-release.sh
scripts/init.sh
scripts/join-release.sh
scripts/join.sh

These are some small fixes needed for rktlet clusters to run.

Fixes for running rktlet clusters

---

doc/troubleshooting.md

Describe briefly how to debug problems of kubeadm init blocking.
Fixes https://github.com/kinvolk/kube-spawn/issues/143

doc: how to troubleshoot problems of kubeadm blocking

---

README.md
doc/troubleshooting.md

In `troubleshooting.md`, add a section about how to troubleshoot insecure registry issues, and update `README.md` too.
Fixes https://github.com/kinvolk/kube-spawn/issues/141
Fixes https://github.com/kinvolk/kube-spawn/issues/142

doc: describe how to set up an insecure registry

---

README.md

Fixes https://github.com/kinvolk/kube-spawn/issues/175

readme: add instruction to get kubectl

---

README.md

Following https://github.com/kinvolk/kube-spawn/pull/228, add the logo in the README.md.
Fixes https://github.com/kinvolk/kube-spawn/issues/227

README.md: add logo

---

doc/troubleshooting.md

Some ISPs do DNS hijacking. Explain how to troubleshoot this and how to work around this.

doc: troubleshooting hijacking DNS

---

README.md

Let's point out that kube-spawn is a certified kubernetes distro.

Add certification info to README

---

cmd/kube-spawn/create.go
pkg/config/defaults.go

Set the default Kubernetes version to v1.8.5, as it's k8s v1.8.x tree has been stable since months.

cmd,pkg: upgrade the default Kubernetes version to v1.8.5

---

doc/devel/release.md

Add smoke test, check version.
-----
~I would like to merge this only after v0.2.0, so if I notice anything else during the release, I can add it to this PR.~

doc/devel/release.md: updates

---

cmd/kube-spawn/create.go
cmd/kube-spawn/kube-spawn.go
cmd/kube-spawn/start.go
pkg/bootstrap/util.go

Another fix for overlay check and for flags parsing

---

pkg/cluster/clusterfiles.go

Disable kubelet eviction / allocatable enforcement

---

.travis.yml
cmd/kube-spawn/kube-spawn.go
pkg/bootstrap/cninet.go
pkg/bootstrap/node.go
pkg/cluster/cluster.go
pkg/machinectl/machinectl.go

This PR fixes a few lint/fmt errors.
It then adds lint & fmt to the pipeline to prevent checking in code w/ fmt errors.

Add gofmt check

---

pkg/machinectl/machinectl.go

In newer versions of systemd a single-character unicode ellipsis (…) is
used instead of three dots (...), handle this case.
Also, try to parse the IP and return an error if that fails.

pkg, machinectl: handle unicode ellipsis

---

README.md

Add a section of community, including our slack channel on https://kubernetes.slack.com.

README: add a community section
